Выполняет задание 3
htmlacademy-react/1479977-what-to-watch-7 pull request #3
Opened 2021-06-01 14:50 UTC by iv-tsim

- Сначала создал просто массив на 20 элементов new Array(20) и вывел методом map компонент FilmCard, линтер заругался на то, что нет ключей, попробовал просто индекс использовать в разных вариациях, как в демонстрации, но линтер уже заругался на то, что нельзя использовать индекс, как ключ. В итоге пришлось создать уже массив FILMS из объектов, в которых указывается id. Не уверен, правильно ли я сделал.
 - Еще линтер ругается на неправильные пути к картинкам, но, как я понимаю, это не исправить.

2021-06-01 19:36 UTC, dtsaryov requested changes

2021-06-01 19:36 UTC, dtsaryov commented on project/src/components/main/main.jsx
> +            {FILMS.map((film) => <FilmCard key={film.id}/>)}
Обмануть Eslint можно так: 

`{new Array(20).fill(null).map((_, idx) => idx + 1).map((key) => <FilmCard key={key}/>)}`

И в данный момент в этом ничего плохо нет

2021-06-01 19:36 UTC, dtsaryov commented on project/src/components/filmCard/filmCard.jsx
> +import React from 'react';
> Б21. Название файла совпадает с названием экспортируемого модуля. В названии файлов не используется разный регистр, а применяется разделение слов дефисом. Исключение составляют файлы, которые были созданы автоматически во время создания проекта.

Это же относится и к имени папки

2021-06-01 19:36 UTC, dtsaryov commented on project/src/components/main/main.jsx
> +  const FILMS = [
1. Все константы нужно объявлять вне функции
2. Вместо хардкода можно было через цикл / map сгенерировать
3. Нужно удалить (см далее)

2021-06-01 19:36 UTC, dtsaryov commented on project/src/index.js
> +    <App promoName={'The Grand Budapest Hotel'} promoGenre={'Drama'} promoDate={2014} />
Давай объявим объект снаружи ReactDOM.render и туда всё это сложим (promoName, promoGenre, promoDate)

2021-06-01 19:36 UTC, dtsaryov commented on project/src/components/app/app.jsx
> +  return <Main promoName={'The Grand Budapest Hotel'} promoGenre={'Drama'} promoDate={2014} />;
Пропсы передали, а заиспользовать забыли

2021-06-01 19:36 UTC, dtsaryov commented
> Еще линтер ругается на неправильные пути к картинкам, но, как я понимаю, это не исправить

Не на картинки, а на `#` в атрибутах `href` - ничего страшного

2021-06-01 19:50 UTC, iv-tsim commented on project/src/components/filmCard/filmCard.jsx
> +import React from 'react';
То есть вместо названий папки и файла filmCard должны быть film-card, а название компонента - ок (как я понял из лайва, нужно объявлять компоненты с большой буквы)?

2021-06-03 08:52 UTC, dtsaryov commented on project/src/components/filmCard/filmCard.jsx
> +import React from 'react';
Ага

2021-06-03 08:53 UTC, dtsaryov approved these changes

2021-06-03 08:53 UTC, merged